FROM python:3.8-alpine

RUN mkdir /app
COPY ./src /app

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./compose/entrypoint /entrypoint
RUN sed -i 's/\r$//g' /entrypoint
RUN chmod +x /entrypoint

COPY ./compose/start /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start

# Server
EXPOSE 5000
STOPSIGNAL SIGINT
ENTRYPOINT ["/entrypoint"]
