#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

mongo_ready(){
python << END
import sys
from pymongo import MongoClient
from pymongo.errors import ServerSelectionTimeoutError
try:
    client = MongoClient("${MONGO_URI}")
    db=client.admin
    serverStatusResult=db.command("serverStatus")
except ServerSelectionTimeoutError:
    sys.exit(-1)
sys.exit(0)

END
}

until mongo_ready; do
    >&2 echo 'Waiting for Mongodb become available....'
    sleep 1
done
>&2 echo 'Mongodb is available'

exec "$@"
